#!/usr/bin/env node
// @effect-diagnostics nodeBuiltinImport:off -- a one-shot codegen script run outside any Effect runtime; it only reads files and writes one module.
// @effect-diagnostics globalConsole:off -- its single line of output is for the developer running it.
/**
 * Embeds the weContain guest services the sandbox image ships (dreamfeed and
 * the lateral goal-loop engine) into a TypeScript module.
 *
 * The sandbox image is rendered from data at build time (see
 * `src/sandbox/image.ts`), so its extra files have to travel inside the server
 * bundle rather than as loose assets. Re-run this whenever the weContain
 * sources change:
 *
 *   node apps/server/scripts/generate-sandbox-guest-assets.ts [--from <weContain dir>]
 *
 * `--from` defaults to `../weContain` relative to the t3code root.
 */

import * as NodeChildProcess from "node:child_process";
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";
import * as NodeURL from "node:url";
import * as NodeZlib from "node:zlib";

const t3codeRoot = NodePath.resolve(NodeURL.fileURLToPath(new URL("../../..", import.meta.url)));
const fromIndex = process.argv.indexOf("--from");
const weContainRoot = NodePath.resolve(
  fromIndex === -1 ? NodePath.join(t3codeRoot, "..", "weContain") : process.argv[fromIndex + 1]!,
);
const outputPath = NodePath.join(t3codeRoot, "apps/server/src/sandbox/guestAssets.generated.ts");

/** lateral trees that run inside the sandbox. Tests, docs and scripts stay out. */
const LATERAL_ENTRIES = ["package.json", "bin", "src"];

const WORKSPACE_DEFAULT = 'WS="${DREAMFEED_WORKSPACE:-$HOME/workspace}"';
const WORKSPACE_OVERRIDE = 'WS="${DREAMFEED_WORKSPACE:-${T3_SANDBOX_WORKSPACE:-$HOME/workspace}}"';

function readDreamfeed(): string {
  const source = NodeFS.readFileSync(NodePath.join(weContainRoot, "guest/dreamfeed.sh"), "utf8");
  const normalized = source.replaceAll("\r\n", "\n");
  // T3 sandboxes clone into a project-named guest dir instead of ~/workspace;
  // dreamfeed must follow the same override the start script uses.
  if (!normalized.includes(WORKSPACE_DEFAULT)) {
    throw new Error(`dreamfeed.sh no longer contains ${WORKSPACE_DEFAULT}; update this generator`);
  }
  return normalized.replace(WORKSPACE_DEFAULT, WORKSPACE_OVERRIDE);
}

function listFiles(root: string, relative: string): string[] {
  const absolute = NodePath.join(root, relative);
  if (NodeFS.statSync(absolute).isFile()) {
    return [relative];
  }
  return NodeFS.readdirSync(absolute)
    .toSorted()
    .flatMap((entry) => listFiles(root, NodePath.posix.join(relative, entry)));
}

const TAR_BLOCK = 512;

function tarHeader(entryPath: string, size: number, mode: number): Buffer {
  const block = Buffer.alloc(TAR_BLOCK);
  const octal = (value: number, offset: number, length: number) =>
    block.write(value.toString(8).padStart(length - 1, "0"), offset, length - 1, "ascii");
  if (Buffer.byteLength(entryPath) > 99) {
    throw new Error(`path too long for a ustar entry: ${entryPath}`);
  }
  block.write(entryPath, 0, 99, "utf8");
  octal(mode, 100, 8);
  octal(1000, 108, 8);
  octal(1000, 116, 8);
  octal(size, 124, 12);
  octal(0, 136, 12);
  block.write("        ", 148, 8, "ascii");
  block.write("0", 156, 1, "ascii");
  block.write("ustar\0", 257, 6, "ascii");
  block.write("00", 263, 2, "ascii");
  let checksum = 0;
  for (const byte of block) checksum += byte;
  block.write(`${checksum.toString(8).padStart(6, "0")}\0 `, 148, 8, "ascii");
  return block;
}

/** Deterministic gzipped tarball: sorted entries, zero mtimes, LF line endings. */
function packLateral(): Buffer {
  const lateralRoot = NodePath.join(weContainRoot, "lateral");
  const files = LATERAL_ENTRIES.flatMap((entry) => listFiles(lateralRoot, entry));
  const blocks: Buffer[] = [];
  for (const file of files) {
    const raw = NodeFS.readFileSync(NodePath.join(lateralRoot, file));
    const bytes = /\.(js|json|html|css|md)$/.test(file)
      ? Buffer.from(raw.toString("utf8").replaceAll("\r\n", "\n"), "utf8")
      : raw;
    const executable = file === "bin/lateral.js";
    blocks.push(tarHeader(`lateral/${file}`, bytes.byteLength, executable ? 0o755 : 0o644));
    blocks.push(bytes);
    const remainder = bytes.byteLength % TAR_BLOCK;
    if (remainder !== 0) blocks.push(Buffer.alloc(TAR_BLOCK - remainder));
  }
  blocks.push(Buffer.alloc(TAR_BLOCK * 2));
  return NodeZlib.gzipSync(Buffer.concat(blocks), { level: 9 });
}

function sourceRevision(): string {
  try {
    return NodeChildProcess.execFileSync(
      "git",
      ["-C", weContainRoot, "rev-parse", "--short", "HEAD"],
      {
        encoding: "utf8",
      },
    ).trim();
  } catch {
    return "unknown";
  }
}

const dreamfeed = readDreamfeed();
const lateral = packLateral();

const output = `// Generated by apps/server/scripts/generate-sandbox-guest-assets.ts — do not edit.
// Source: weContain @ ${sourceRevision()} (guest/dreamfeed.sh, lateral/{${LATERAL_ENTRIES.join(",")}}).
// Regenerate after changing those sources.

/** weContain's dreamfeed guest service (docs/04-dreamwalking.md). */
export const DREAMFEED_SCRIPT: string = ${JSON.stringify(dreamfeed)};

/** Gzipped ustar of the lateral goal-loop engine, rooted at \`lateral/\`. */
export const LATERAL_BUNDLE_BASE64: string =
  ${JSON.stringify(lateral.toString("base64"))};
`;

NodeFS.writeFileSync(outputPath, output);
console.log(
  `wrote ${NodePath.relative(t3codeRoot, outputPath)} (dreamfeed ${dreamfeed.length} B, lateral ${lateral.byteLength} B gz)`,
);
